### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by PipeDeveloper** [Hydrosys4/Master#4]
Hello! and thank for share your proyect.

I have installed on a fresh raspbian on raspberry pi 3, following step by step. But on step 5, i connected with my phone, also directly from raspberry and with my PC all with this message.

![WhatsApp Image 2019-04-12 at 17 17 07](https://user-images.githubusercontent.com/35433329/56066950-557fa280-5d47-11e9-89c8-5c13a0255381.jpeg)

How can i solve this? before buy all hardware for the proyect i want to test the interface and see if the GPIO works as spected. thank you very much!

**Comment by PipeDeveloper** [comment]
And yes, all information (port is right)
![WhatsApp Image 2019-04-12 at 17 34 04](https://user-images.githubusercontent.com/35433329/56067519-6c26f900-5d49-11e9-8b43-20b6c3f68c0a.jpeg)

**Comment by Hydrosys4** [comment]
Hi, as I see from the screenshot, it is not a connection problem. Seem that the python script did not started properly. May I ask which raspbian did you use? Is it the April 2019? I did not test the installation with such release yet. 
To test the system you can also directly download the SD image file, you can find it on the hydrosys4 website that is linked in the description.
Thanks

**Comment by Hydrosys4** [comment]
In the last release of Raspbian lite the hostapd service has been masked. 
I updated the installation guide on the site https://hydrosysblog.wordpress.com/configuration/ 
to solve the issue.
