### ISSUE TITLE
Install fails with install script

### ISSUE THREAD

**Issue by knockimov** [Hydrosys4/Master#6]
Your install script needs to be updated to Python3 as Python2.7 has reached EOF as of january this year. Because of this, including the bellow statesment, the script fails to install.

The script also needs to be updated so it reflects correct paths and required packages.
- Pip3 has to be used instead of ordinary pip
- The path for Nginx copy default configuration is wrong
- Squid3 is not active to be installed
- Python Tornado web server is not configured, Nginx is used.

In the attached file I have made those adjustments.
[install_hydrosys4.txt](https://github.com/Hydrosys4/Master/files/4596031/install_hydrosys4.txt)

**Comment by Hydrosys4** [comment]
Thanks, 
Maybe its time to upgrade the whole project to python3

**Comment by Hydrosys4** [comment]
The project has been ported to python3 now!
