### ISSUE TITLE
Feature request: Restart och shutdown the system

### ISSUE THREAD

**Issue by knockimov** [Hydrosys4/Master#7]
Hello,

I would like to request a new feature. I would like to be able to restart or even shutdown the system from the webpage.
There is no problem using ssh, but for those that do not know how it would be a nice addition.

**Comment by Hydrosys4** [comment]
Thanks for the suggestion, I'll add to the todo list.

**Comment by knockimov** [comment]
Hello, 

I have updated your install script again :). I hope you don't mind?! 

I have used the latest published script from
https://github.com/Hydrosys4/Master/blob/master/bash/install_hydrosys4.sh
as a start. The changes made as described below. 

 	* The script now checks if packages are installed or not, if not it
will install them, for both apt and pip3.
 	* There is now a check if the script is running as root or with sudo
privileges It will exist if not running as root or with sudo.
 	* The default install path is changed from /home/pi/env/autonom to
/usr/local/share/hydrosys4/env/autonom to accommodate other potential
distros and user.
 	* I have also reordered your code a bit to be more easily readable
including removing sudo command.

On my todo/wish list i have the following. 

	* Make the script accept commands like 

 	* --install (perhaps not necessary)
 	* --update
 	* --reinstall
 	* --uninstall

 	* Make the script able to choose i2c address automatically if device
is present and add the to new device.

	* Adding sections and questions in input_UI() in the script to
accommodate more and different sensors/actuators like 

 	* Light sensor
 	* Soil sensor
 	* Temperature/humidity sensor and what type (dht22 or ds18b)
 	* Wind sensor

By the way, where are you from? I'm from Sweden :) 

Best regards, 

Pierre Tunander 

2020-05-18 21:36 skrev Angelo:

> Closed #7 [1]. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].

-- 

Med vänliga hälsningar,

Pierre Tunander
Doktor Wengbergs Gata 36
413 25 Göteborg 

Links:
------
[1] https://github.com/Hydrosys4/Master/issues/7
[2] https://github.com/Hydrosys4/Master/issues/7#event-3348821111
[3]
